using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace WinUI.SingleInstanced.SourceGenerator.Generators
{
    [Generator(LanguageNames.CSharp)]
    public class ProgramGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var assemblyNameProvider = context.CompilationProvider.Select((compilation, _) => compilation.AssemblyName);
            context.RegisterSourceOutput(assemblyNameProvider, (context, assemblyName) =>
            {
                if (assemblyName == null) return;
                context.AddSource("Program.g.cs", SourceText.From(
                    GenerateSource(assemblyName),
                    Encoding.UTF8));
            });
        }

        private static string GenerateSource(string rootNamespace)
        {
            return $@"// <auto-generated />
namespace {rootNamespace}
{{
    /// <summary>
    /// Auto-generated Program.cs by WinUI.SingleInstanced
    /// </summary>
    public static partial class Program
    {{
        /// <summary>
        /// Invoked when the application is activated. Subscribe to it to handle activation arguments.
        /// </summary>
        public static event global::System.EventHandler<global::Microsoft.Windows.AppLifecycle.AppActivationArguments>? Activated;

        private static readonly global::WinUI.SingleInstanced.Manager _manager;

        static Program()
        {{
            _manager = new global::WinUI.SingleInstanced.Manager(
                ""{rootNamespace}"",
                () => new global::{rootNamespace}.App(),
                (sender, activationArgs) => 
                {{
                    Activated?.Invoke(sender, activationArgs);
                }}
            );
        }}

        [global::System.STAThread]
        static void Main(string[] args)
        {{
            _manager.Activate();
        }}
    }}
}}
";
        }
    }
}
